# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job:
        displayName: Build Job
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - bash: echo contents in the System default Working Directory; ls -R $(System.DefaultWorkingDirectory)
            displayName: Display Contents in System default Working Directory
          - bash: echo Before copying contents in the Build Artifactory Directory; ls -R $(Build.ArtifactStagingDirectory)
            displayName: Display Contents in Artifactory Directory Before Copying 
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              OverWrite: true
          - bash: echo After copying contents to the Build Artifactory Directory; ls -R $(Build.ArtifactStagingDirectory)
            displayName: Display Contents in Artifactory Directory After Copying
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'terraform-manifest'
              publishLocation: 'Container'